steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/express-app', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/express-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'express-app', 
           '--image', 'gcr.io/$PROJECT_ID/express-app',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated']

# Substitutions to make the config dynamic
substitutions:
  _SERVICE_NAME: "express-app"
  _REGION: "us-central1"

# Set permissions
images:
  - 'gcr.io/$PROJECT_ID/express-app'
